#!/bin/bash

set -x
set -e

logfile=/tmp/qemu-hook-log.txt
echo "`date`: invoked with args $*" >> ${logfile}

function radeon-reset() {
    radeon="0000:23:00"

    setpci -s "${radeon}.0" 7c.l=39d5e86b

    sleep 1

    echo "1" | tee -a "/sys/bus/pci/devices/${radeon}.0/remove"
    echo "1" | tee -a "/sys/bus/pci/devices/${radeon}.1/remove"
    sleep 1
    echo "1" | tee -a /sys/bus/pci/rescan

    sleep 2

    # for some reason the clock may slip, on my machine 8 seconds means almost immediate wakeup
    rtcwake -m mem -s 10 -u -v > /tmp/suspend.txt >> ${logfile}
    echo "1" | tee -a /sys/bus/pci/rescan
}

case "$1-$2-$3" in
    catalina-release-end)
        if [ ! -f /tmp/going-to-shutdown ]; then
            radeon-reset
        fi

    ;;
    *)

    ;;
esac



