#!/bin/bash -xe

mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev 

mount --rbind /mnt/boot /mnt/gentoo/boot
mount --make-rslave /mnt/gentoo/boot
